### ISSUE TITLE
Create Post not working for me

### ISSUE THREAD

**Issue by mgbowe1** [mgbowe1/COMP3100-Project#2]
Hi @JPPerkins ,

The Create Post functionality is not working for me and I'm unsure how post comment is supposed to work.

Regards,
Michael

**Comment by raghnall6402** [comment]
Hm, is it giving any information for the create post? It should be working. As far as post comment, right now without getting any userfeed working, the user inputs the parent tweet id into the field, with their body in the original "Create Post" field then click the Comment button. It's not ideal, but it was just to get anything implemented.

I've been working on trying to parse the JSON for userfeed as well as keyword search, but they are giving me issues.

**Comment by mgbowe1** [comment]
Give me a call to coordinate since I was working on the json parsing as well.

On May 2, 2018 21:37, raghnall6402 <notifications@github.com> wrote:

Hm, is it giving any information for the create post? It should be working. As far as post comment, right now without getting any userfeed working, the user inputs the parent tweet id into the field, with their body in the original "Create Post" field then click the Comment button. It's not ideal, but it was just to get anything implemented.

I've been working on trying to parse the JSON for userfeed as well as keyword search, but they are giving me issues.

**Comment by mgbowe1** [comment]
My phone is (978)-875-1954

On May 2, 2018 21:37, raghnall6402 <notifications@github.com> wrote:

Hm, is it giving any information for the create post? It should be working. As far as post comment, right now without getting any userfeed working, the user inputs the parent tweet id into the field, with their body in the original "Create Post" field then click the Comment button. It's not ideal, but it was just to get anything implemented.

I've been working on trying to parse the JSON for userfeed as well as keyword search, but they are giving me issues.

**Comment by mgbowe1** [comment]
The problem is that we are not sanitizing input. I had an apostrophe in the input which broke the query. Expanding the contraction I'm to I am solved my posting problem, but we need to fix this issue.

**Comment by mgbowe1** [comment]
Committed fix
